### ISSUE TITLE
Number of BNFs Calculated in Distribution is Wrong - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#1013]
![image](https://user-images.githubusercontent.com/31128624/61939206-075b7b80-af93-11e9-97a1-60eee875fbb6.png)

**Comment by bamoure** [comment]
Not sure what's the issue here, it says 1 and there's only one

**Comment by Happs80** [comment]
Please see the values highlighted in red here.

![image](https://user-images.githubusercontent.com/31128624/62124807-786c9d00-b2cb-11e9-9a41-865ab6df5c66.png)

**Comment by bamoure** [comment]
This is a display bug on the table that has been fixed since on the test server (will deploy on the production server this week)

**Comment by Happs80** [comment]
ah ok. thanks.
