### ISSUE TITLE
Beneficiary Search Bar Text Overrun

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#463]
In search bar, if project name is long, it overruns the drop down arrow and prevents further interaction. 

![pasted image 0](https://user-images.githubusercontent.com/31128624/54068675-f3cca400-4281-11e9-8a0a-487e86cf253a.png)

**Comment by barbaraReliefapps** [comment]
Already fixed 
<img width="282" alt="Capture d’écran 2019-03-11 à 09 04 21" src="https://user-images.githubusercontent.com/36275616/54096038-afa1e680-43dc-11e9-965a-aa45ce1fed07.png">
