### ISSUE TITLE
Add ‘Completed’ icon to distribution table - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#465]
(Representing percentage distributed).

![pasted image 0 (1)](https://user-images.githubusercontent.com/31128624/54068807-38a50a80-4283-11e9-95d2-bc4f9172140e.png)

**Comment by Happs80** [comment]
I cannot see this??

**Comment by barbaraReliefapps** [comment]
This is just a checkbox to show when a distribution has been completed (either manually or because all items were distributed), as per the stage 2 specifications

**Comment by Happs80** [comment]
Yes, can we not add the above, so user can see status of distribution from the table?

**Comment by barbaraReliefapps** [comment]
We can only see if it's completed/closed or not

**Comment by Happs80** [comment]
but we have the percentage complete on the other page?

**Comment by barbaraReliefapps** [comment]
Yes, but that is a calculation that is done on this page where we have all the information on the distribution and its beneficiaries
From this "general" page we can only see if it's validated or not and if it's completed or not
