### ISSUE TITLE
Add pinch to zoom in map panel - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#466]
Map should allow for mouse/touch interactions inside the fame (pinch to zoom etc.) Currently zooms entire window. (remove the click before zooming).

**Comment by Nastaliss** [comment]
Pinch to zoom is already implemented. 
What is the problem here?

**Comment by Happs80** [comment]
Sorry, not as clear as I should have been.

When using mouse or trackpad, you have to click to pinch and zoom at the moment, but it would be good if it could be functioning without having to click.

**Comment by Nastaliss** [comment]
@barbaraReliefapps I think we should take that into account when redoing the map in Stage 2
