### ISSUE TITLE
Update Sector List - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#470]
Camp Coordination & Management
Education
Early Recovery
Emergency Telecommunications
Food Security & Livelihoods
Logistics
Nutrition
Shelter
WASH
Mine Action
DRR & Resilience
Non-Sector Specific

**Comment by Happs80** [comment]
Our designer is working on these and we will send through soon.

**Comment by barbaraReliefapps** [comment]
Closing as it is ignored due to the Stage 2 requirements
