### ISSUE TITLE
Small Visual Changes

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#477]
- Need to check all text for Sentence Caps again.
- Export button on all pages should be in alignment with end of table row. 
- ‘New +’ button seems to be arial font.
- 'Idp' field should be all caps on Add Beneficiary page and in file import template.
- All buttons should have text running aligned from the top, not middle. 
- On Add New Distribution page, Dateofbirth should be ‘Date of Birth’.
- On 'Import Beneficiary Data' page, Download Template and Import button should be aligned right together.
- In Chrome, country text in country icon top right of screen is not aligned centre.
- Spacing between Title and content should be the same on every page. For example on 'Beneficiaries' page, there is larger spacing between title and table, than on the front page.
- On 'Distributions' page, the little 'Beneficiaries +' icon needs to be centred with the text.

**Comment by barbaraReliefapps** [comment]
- "All buttons should have text running aligned from the top, not middle."
What do you mean by that?

- "In Chrome, country text in country icon top right of screen is not aligned centre."
We can't seem to reproduce the issue on any browser

- "On 'Distributions' page, the little 'Beneficiaries +' icon needs to be centred with the text."
Where is this ?

**Comment by Happs80** [comment]
- the text and the + on these buttons are not aligned.

- still not aligned in my chrome browser. sorry. have also replicated on other PCs in chrome.

- not centred. please see attached images.
![Add](https://user-images.githubusercontent.com/31128624/54657010-69decf80-4afa-11e9-9123-d96863953c62.PNG)
![create](https://user-images.githubusercontent.com/31128624/54657014-6cd9c000-4afa-11e9-80bd-5022e44fac32.PNG)
![countryicon](https://user-images.githubusercontent.com/31128624/54657016-6f3c1a00-4afa-11e9-9212-c2a11711a809.PNG)
