### ISSUE TITLE
Search Bar Update - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#481]
- Search field should have a little magnifying glass button. 
- Underline should not extend the length of the frame, but perhaps only 25%.
- Advanced Options text should align to the left of the table.

**Comment by colinethrl** [comment]
![Screenshot from 2019-05-08 10-59-56](https://user-images.githubusercontent.com/40642639/57363359-40006b80-7181-11e9-979e-06ac526b7284.png)

To be honest the 25% width looks a bit weird, doesn't it ?

**Comment by Happs80** [comment]
Perhaps, but i think the long line just looks like a page break, whereas this clearly draws the eye as a search bar.
