### ISSUE TITLE
Close Distribution Function - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#483]
Need to have function to ‘Close Distribution’ on Distribution Page, with timestamp recorded. Needs confirmation message. Once clicked, can no longer edit or change any distribution details. Icon in Distribution Table should change to 'Tick' icon.

**Comment by Reliefapps** [comment]
what the difference with validate a distribution (is it only to add the timepstamp) ?

**Comment by Happs80** [comment]
This was a request from users.

So when handing out vouchers for example, some people do not pick up the vouchers for whatever reason, so if you looked at the distribution progress, it would appear to be unfinished. However, sometimes there are valid reasons for people not picking up vouchers, and the team wants to finalise the distribution anyway, so they wanted to be able to mark it as 'closed' or 'finished'.
