### ISSUE TITLE
Default Fonts Not Displaying in Firefox - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#484]
Lato Light reverting to Aerial in Firefox.

**Comment by Nastaliss** [comment]
Could you tell us what version of firefox you are using?
Using firefox 66.0.3 I am indeed seing the Lato font used in the app.

**Comment by Happs80** [comment]
Please open again.

See here.

![image](https://user-images.githubusercontent.com/31128624/57369093-f9c5ff00-71b6-11e9-8980-def6f70631fc.png)

**Comment by barbaraReliefapps** [comment]
Same version of Firefox, and it is Lato, it is just displayed differently on Chrome and on Firefox
![Capture d’écran 2019-05-08 à 12 35 52](https://user-images.githubusercontent.com/36275616/57369446-d9ce1580-718d-11e9-862a-ec5f88a98caa.png)

**Comment by Happs80** [comment]
No. This appears differently than default lato.

Please re-open.

![image](https://user-images.githubusercontent.com/31128624/58008363-842e2d00-7aec-11e9-9e7b-89b4b190b2b3.png)

**Comment by barbaraReliefapps** [comment]
It really does appear to be the same thing (left side firefox and right side chrome)
<img width="1097" alt="Capture d’écran 2019-05-21 à 11 16 16" src="https://user-images.githubusercontent.com/36275616/58068005-c83b3380-7bb9-11e9-85cb-f450f986b622.png">

**Comment by Happs80** [comment]
That's a mac. Check a PC. :)
