### ISSUE TITLE
Export Beneficiaries Function Very Slow - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#505]

**Comment by barbaraReliefapps** [comment]
The more beneficiaries there are, the more time it will take to generate the file. The only way to improve this is with a bigger server

**Comment by Happs80** [comment]
But we're only talking a few hundred beneficiaries. Should it really be that slow?

**Comment by barbaraReliefapps** [comment]
If it's that slow it's probably a problem with your internet connection. We can try and see if we can speed up the process on our end but I don't think there's a lot we can do

**Comment by Happs80** [comment]
We're running on a 80mbps connection here in the office. I don't think bandwidth is the issue.

**Comment by barbaraReliefapps** [comment]
How long does it take?

**Comment by Happs80** [comment]
I will keep monitoring this, but let's close for now. Thanks.
