### ISSUE TITLE
More Small Visual Changes

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#534]
- HAVE TO CHECK TITLE CASE AGAIN!
- Layout of Add Beneficiary 'Head' and 'Members' pages needs to be cleaned up. maybe four even columns? Also some of the rows are out of alignment.
- On Login page, form boxes should be same width as Captcha box. And also same buffer gap between boxes.

![add benef layout](https://user-images.githubusercontent.com/31128624/54813548-5d0bd880-4cc0-11e9-9893-6bb8fae0b41d.PNG)
![login](https://user-images.githubusercontent.com/31128624/54813550-5ed59c00-4cc0-11e9-880e-0c65619e5fd1.PNG)
![title](https://user-images.githubusercontent.com/31128624/54893046-a0479080-4ee6-11e9-8c4e-5a82049247ee.PNG)

**Comment by barbaraReliefapps** [comment]
titlecase for vulnerability criteria fixed
