### ISSUE TITLE
Cannot Change Password Error Needs Reason

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#535]
When trying to change password, it simply says 'Error' but does not provide an explanation why.

**Comment by Nastaliss** [comment]
Are you talking about 
![this modal](https://user-images.githubusercontent.com/46960549/55090866-2236e580-50b0-11e9-8ef9-f804870b706a.png)

**Comment by Happs80** [comment]
Yes.

It is occurring in my own account, when i go to user profile and try to change it there.
