### ISSUE TITLE
When Adding New Project, Select from List of Project Managers

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#536]

**Comment by barbaraReliefapps** [comment]
What do you mean by this?

**Comment by Happs80** [comment]
Currently you have to go into settings, users, user and then apply project
to user. It would be much quicker, if when setting up a project, there was
a drop down with all project managers and you can associate them with the
project.

**Comment by Reliefapps** [comment]
are you sure of this one? most of the sites (including Github) have the user management after the project creation. We have not included this one in the phase 2 as of now waiting for your answer

**Comment by Happs80** [comment]
I cannot log in to test this, because i am getting an error!

But as far as i can see from testing, the project managers cannot create
and assign projects to themselves?
