### ISSUE TITLE
Export Function on Distribution Page Not Exporting All Information

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#539]
On the Distribution Page, if you click the export button, it only exports a limited number of fields.

**Comment by barbaraReliefapps** [comment]
What fields do you want to export?

**Comment by Happs80** [comment]
DistributionID (When it becomes available)
Project Name
Distribution Start Date
Location
Beneficiary Type
Number of Beneficiaries Total
Percentage Distributed
Commodity
Criteria Selections

**Comment by barbaraReliefapps** [comment]
Fixed in backend https://github.com/ReliefApplications/bms_api/pull/242
