### ISSUE TITLE
Prevent step bypass when adding households - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#542]

**Comment by Nastaliss** [comment]
Could you provide us with further information on how to reproduce this bug?
Creating an houshold resulted in the follwing summary: 
![Screenshot from 2019-03-27 16-58-52](https://user-images.githubusercontent.com/46960549/55091743-ad64ab00-50b1-11e9-85ad-aa88b1eb2e20.png)

**Comment by Happs80** [comment]
This is occurring in Chrome. Under KHM. In any household I look at.

![image](https://user-images.githubusercontent.com/31128624/55125624-e5650000-513c-11e9-9c9f-ccbe57d3b85c.png)
![image](https://user-images.githubusercontent.com/31128624/55125651-f44bb280-513c-11e9-96e5-a9bcdc0c0ba0.png)
![image](https://user-images.githubusercontent.com/31128624/55125655-f9a8fd00-513c-11e9-8aaa-0dab94b68bf7.png)

**Comment by Nastaliss** [comment]
This is because you skipped step 2 on your first screenshot.
Clicking directly on the stepper (progress bar at he top) instead of next allow the user to bypass certain steps even if they are required.
Updating the issue.
