### ISSUE TITLE
Application Access in Northern Syria

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#545]
As users in Northern Syria are receiving their Internet connection from Turkey ISPs, their IP addresses are most likely appearing as Turkish IPs. Which is preventing them from logging in to the platform. Is there a way to make an exception for this unique scenario?

**Comment by Nastaliss** [comment]
This issue will be fixed on the server-side.
https://github.com/ReliefApplications/bms_api/issues/225

**Comment by Happs80** [comment]
Our user is still having this issue.

![image](https://user-images.githubusercontent.com/31128624/55207152-b1a4db80-520b-11e9-84ea-df272560054c.png)
