### ISSUE TITLE
Very Slow to Load Admin Areas - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#569]
When manually selecting admin areas from the drop down menus on the 'Add Beneficiary' and 'Add New Distribution' page, the drop down menu options take a long time to load.

**Comment by barbaraReliefapps** [comment]
There are a lot of locations for each admin area, there isn't much we can do.
It depends on the internet connection: I tried on the test server and they appeared almost immediately

**Comment by Happs80** [comment]
Ok.
