### ISSUE TITLE
WING Error Message Needs Translation - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#581]
Wing Error: "No Range Slab Defined For Transaction" means that transaction amount is too small or too large. Must be > $1.00 or < $1,000.

**Comment by barbaraReliefapps** [comment]
We cannot translate error messages from financial API, they are passed directly

**Comment by Happs80** [comment]
There is no way to display a plain english version of this?

**Comment by barbaraReliefapps** [comment]
We can only display the error WING gives us, we can't "analyse" and translate each error we get back from them into something comprehensible by all
