### ISSUE TITLE
Error Message on Project Page - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#585]
![image](https://user-images.githubusercontent.com/31128624/56136505-46625400-5fd6-11e9-9430-4369a432b840.png)

**Comment by Nastaliss** [comment]
Could you provide more information on how to replicate this bug ?

This looks like a connection error that occurs when the user is not properly logged in.

**Comment by Happs80** [comment]
It seems to occur when flicking quickly between pages. Doesn't seem to be always replicable.

**Comment by barbaraReliefapps** [comment]
We haven't been able to replicate this issue, on any browser even when changing network speed. Is it okay if we close this for now or is it still happening frequently for you?

**Comment by Happs80** [comment]
Sorry, i missed this comment. Yes ok to close.
