### ISSUE TITLE
Voucher Module - Modality Selection - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#598]
If adding a distribution with QR Code Vouchers, then the unit type should be fixed as 'Voucher'.

**Comment by barbaraReliefapps** [comment]
Do you mean you want the 'Unit' input to be set as 'Voucher'? And the value to be the number of vouchers that will be distributed per person
If so, on the distribution page should the progression be calculated with the number of vouchers instead of the value of the booklet?

**Comment by Happs80** [comment]
I just meant to be fixed, not user entered.

So I guess it should be booklet then.

**Comment by barbaraReliefapps** [comment]
So in the modality selection, the field 'Unit' would be set as 'Voucher', and the field 'Value' would correspond to what? The number of vouchers in the booklet distributed? The value of the booklet?

**Comment by Happs80** [comment]
No no. Unit set as 'Booklet'.

Then just select number of booklets.

**Comment by barbaraReliefapps** [comment]
As per the specifications we can only have one active booklet per beneficiary per disrtibution

**Comment by Happs80** [comment]
That was in the specifications?

**Comment by barbaraReliefapps** [comment]
I think so? we said that we could deactivate a booklet and assign a new one to a distribution beneficiary, so if we try to assign a booklet to a user that already has one the previous one will be deactivated

**Comment by barbaraReliefapps** [comment]
We can change it to accomodate multiple booklets per beneficiary and distribution, if you feel it is necessary

**Comment by Happs80** [comment]
I have checked with the team and only one booklet per household is required at any one time.

So could we set this as 1 booklet defined if you choose 'QR Code Voucher'?

**Comment by barbaraReliefapps** [comment]
Ok. You don't want to put the value of the booklet instead?

**Comment by barbaraReliefapps** [comment]
@colinethrl

**Comment by Happs80** [comment]
Let me double check with the team and come back asap.

**Comment by Happs80** [comment]
Ok checked with team and they would like total value of the booklet.

So could we have currency and value like we do for other distributions?

**Comment by barbaraReliefapps** [comment]
Yes 👍
