### ISSUE TITLE
Mobile Version - Visual Fixes Needed - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#601]
Please see images

Menu Text Overrun (Also, menu does not disappear if you press outside)
![image](https://user-images.githubusercontent.com/31128624/56407949-68e5bd00-62b5-11e9-834b-d16671c4f5a7.png)

Menu Button Text Overrun
![image](https://user-images.githubusercontent.com/31128624/56407990-9fbbd300-62b5-11e9-86f6-92b1dca0c58f.png)

Screen Items pushed off the screen left
![image](https://user-images.githubusercontent.com/31128624/56408074-1bb61b00-62b6-11e9-9367-d96ba8c00487.png)

Cannot scroll down further
![image](https://user-images.githubusercontent.com/31128624/56448583-b7499900-6353-11e9-8a12-3b6fc8dd0a55.png)

**Comment by Happs80** [comment]
Please open again.

This alignment issue not fixed.

![image](https://user-images.githubusercontent.com/31128624/57367932-2d535a00-71b4-11e9-9e28-3fa6314ac9cc.png)

**Comment by barbaraReliefapps** [comment]
Working for me, did you update the page?

**Comment by barbaraReliefapps** [comment]
Aleady fixed, try updating the page?

**Comment by Happs80** [comment]
ok seems ok now. thanks.
