### ISSUE TITLE
Cannot Import Converted File - Critical

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#604]
![image](https://user-images.githubusercontent.com/31128624/56476983-6ec0e580-64e3-11e9-9fbf-bd040435b1ab.png)
[templateSyria (7).xlsx](https://github.com/ReliefApplications/bms_front/files/3101725/templateSyria.7.xlsx)

**Comment by Nastaliss** [comment]
Fixed in https://github.com/ReliefApplications/bms_api/pull/235
