### ISSUE TITLE
Visual Edit - Line and Buttons Should be Green on this modal - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#608]
On the Beneficiary List, the pop up details modal, should be green, not red.

![image](https://user-images.githubusercontent.com/31128624/56562252-36003980-65d3-11e9-9569-79f591f78171.png)

**Comment by barbaraReliefapps** [comment]
Changed so all modals would follow this rule:
- add and delete in red
- view and update in green
