### ISSUE TITLE
Uniformity of Function - Magnifying Glass - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#613]
On Distribution Validated page, the magnifying modal should display same data as ‘Household Information Summary’ from Add New Beneficiary step 4.

**Comment by barbaraReliefapps** [comment]
Not sure I understand, what do you mean by this?

**Comment by Happs80** [comment]
For 'general relief' distributions, don't need Transaction ID and the title of the modal should be: Edit Beneficiary Information.

![image](https://user-images.githubusercontent.com/31128624/57368474-6cce7600-71b5-11e9-9984-2bd80b50c65d.png)

**Comment by barbaraReliefapps** [comment]
We shouldn't put "Beneficiary Information" as it isn't a Beneficiary we're editing but an item of a General Relief Distribution. It might be confusing for the user to see "Beneficiary" when it isn't actually one.
Instead we could put "Edit this General Relief Item (Food, etc)" where Food is the type of item being distributed

**Comment by Happs80** [comment]
So if you add a Note here, it attaches to the distribution??

**Comment by barbaraReliefapps** [comment]
Yes, that's what you asked for for the general relief distributions:
Create new modality for general relief distributions, with ability to set item as distributed (included timestamp of when it was distributed) and add notes

**Comment by Happs80** [comment]
Yes, understand that.

I just mean, is the note attached to the household/individual table or the distribution table in the db?

**Comment by barbaraReliefapps** [comment]
The note is linked to the distributed item

**Comment by Happs80** [comment]
ahah. that makes sense.

Could we make the title:

Edit Distribution Status

**Comment by barbaraReliefapps** [comment]
It's not the distribution either, it's just the specific item handed out to one specific beneficiary in this distribution, which is why we proposed to put "Edit this General Relief Item (Food)" instead

**Comment by Happs80** [comment]
Ok please change to 'Edit Item' then.

**Comment by barbaraReliefapps** [comment]
@colinethrl
