### ISSUE TITLE
Visual Edit - Sentence Cases - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#614]
Could we please check this again, so I don't have to keep raising this issue.

![image](https://user-images.githubusercontent.com/31128624/56792644-9cd45b80-683c-11e9-90cc-47956a88f694.png)

**Comment by barbaraReliefapps** [comment]
Fixed on test server

**Comment by Happs80** [comment]
Done.

**Comment by Happs80** [comment]
![image](https://user-images.githubusercontent.com/31128624/57931548-fe766b80-78b8-11e9-9406-06344837030f.png)

**Comment by Happs80** [comment]
![image](https://user-images.githubusercontent.com/31128624/58084505-4ea44500-7bbb-11e9-87f1-66d2a350d45d.png)

**Comment by Happs80** [comment]
Should be: ID Number

![image](https://user-images.githubusercontent.com/31128624/58085048-48629880-7bbc-11e9-8529-1e4091c1ff7a.png)

**Comment by barbaraReliefapps** [comment]
@colinethrl
