### ISSUE TITLE
Menu Issue Distribution Page - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#617]
Editing beneficiaries directly from the distribution list, there are strange formats and editing them causes big errors.

![image](https://user-images.githubusercontent.com/31128624/57015982-21aee300-6c4a-11e9-9c61-7dfae771133a.png)

![image](https://user-images.githubusercontent.com/31128624/57016150-2d4ed980-6c4b-11e9-923a-1b8a7c642807.png)

**Comment by barbaraReliefapps** [comment]
Fixed on test server, no editing possible from this page

**Comment by Happs80** [comment]
Thanks.
