### ISSUE TITLE
BNF Import Error with Large Dataset - Critical

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#618]
The system crashed with the following error.

![image](https://user-images.githubusercontent.com/31128624/57057432-35565a00-6cdb-11e9-9a15-0ba436fa79a3.png)

[templateSyria (11).xlsx](https://github.com/ReliefApplications/bms_front/files/3136779/templateSyria.11.xlsx)

**Comment by barbaraReliefapps** [comment]
Increased time of php timeout in backend https://github.com/ReliefApplications/bms_api/pull/244
