### ISSUE TITLE
Voucher Module - Visual Edit - Add Vouchers Modal Text - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#622]
Title should be Create New Booklets and Action button should say Create, not Save.

![image](https://user-images.githubusercontent.com/31128624/57057922-f0342700-6cde-11e9-902a-50570b3f993a.png)

**Comment by Happs80** [comment]
Please open again.

**Comment by barbaraReliefapps** [comment]
It has been fixed, try updating your browser

**Comment by Happs80** [comment]
Done. Thanks.
