### ISSUE TITLE
Phone Number Display Should Show 'Phone No. 1' and 'Phone No. 2' for Clarity

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#627]
![image](https://user-images.githubusercontent.com/31128624/57205845-976cd300-6feb-11e9-8eb4-e9fc600877ff.png)

**Comment by Happs80** [comment]
Please open again.

Phone No.1 and Phone No. 2 should be in the hint text above. Also so should Phone Type and Country Ext.

![image](https://user-images.githubusercontent.com/31128624/57366087-7e614f00-71b0-11e9-92c3-cefbdd0bcf60.png)

**Comment by barbaraReliefapps** [comment]
They are once you type something in
![Capture d’écran 2019-05-08 à 12 18 41](https://user-images.githubusercontent.com/36275616/57368424-6a572680-718b-11e9-9353-26d5c8168530.png)

**Comment by Happs80** [comment]
Oh i see.

Then could we change the hint text to the following, so it's actually legible.

Phone Type -> Type
Country Code -> Ext
Phone No. 1 (No Country Code) -> Phone No. 1
Phone No. 2 (No Country Code) -> Phone No. 2
