### ISSUE TITLE
ID Transaction Status Before Transaction - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#630]
Status should be 'Incomplete'.

![image](https://user-images.githubusercontent.com/31128624/57207048-b6239780-6ff4-11e9-964d-adde4175e874.png)

**Comment by barbaraReliefapps** [comment]
This isn't the transaction status, but the transaction ID in the database, since it doesn't exist yet it's undefined

**Comment by Happs80** [comment]
Could we make it 'Not Yet Defined' then?
