### ISSUE TITLE
Completed Transaction Status Change After Transaction Complete - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#631]
Even though transaction was 100% complete, the system is allowing date change. 

![image](https://user-images.githubusercontent.com/31128624/57207200-ec154b80-6ff5-11e9-8e8b-b320a7108bf6.png)

**Comment by barbaraReliefapps** [comment]
Should we change that so the date cannot be changed once the distribution has been validated?

**Comment by Happs80** [comment]
As part of the Stage 2 specifications, there is a specification to be able to 'close' distributions manually. 

So could we apply this same functionality to 'completed' electronic transactions, but just apply it automatically? i.e. once every amount has been 'sent'?

And then after this point, no more changes can be made.

**Comment by barbaraReliefapps** [comment]
No changes can be made once the transaction is validated (ie you cannot change the beneficiaries and - maybe - the date). Closing the distribution is just a boolean to define if a distribution is done/complete, no?

**Comment by Happs80** [comment]
Not quite sure i understand the question?

**Comment by barbaraReliefapps** [comment]
Not really a question. We're just creating a new field "completed" that can either be set manually or automatically when everything has been distributed

**Comment by Happs80** [comment]
Ha. Ok. Yes, that's sounds good.
