### ISSUE TITLE
Text for Transaction Page - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#632]
Text should be 'Sent' not 'Already Sent'.

![image](https://user-images.githubusercontent.com/31128624/57209603-449f1580-7003-11e9-9996-c4ae7fd76f76.png)

**Comment by Happs80** [comment]
Also should be 'Picked Up' not 'Picked up'

**Comment by barbaraReliefapps** [comment]
Already sent is a different status than sent: 
- sent is when the money was just sent
- already sent is when the money was sent in a previous transaction

**Comment by Happs80** [comment]
What do you mean by sent in a previous transaction?

**Comment by barbaraReliefapps** [comment]
Already sent means it was sent before opening the page, sent is set when you click on the transaction button

**Comment by Happs80** [comment]
I think the distinction might be confusing. could we have both as 'Sent'?
