### ISSUE TITLE
Mobile Version - Menu Button Not Operational - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#640]
Currently on adroid phone, using Chrome, tapping menu button does nothing.

**Comment by Nastaliss** [comment]
Do you mean the hamburger menu in the top-left corner ?

**Comment by barbaraReliefapps** [comment]
Fixed on test server

**Comment by Happs80** [comment]
Please open again.

Now the menu bar is staying open and won't close.

**Comment by barbaraReliefapps** [comment]
Working for me, did you update the page?

**Comment by Happs80** [comment]
Yep. Working now.
