### ISSUE TITLE
Error Message on Login Screen

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#645]
When opening front.bmstaging.info for first time in new browser (firefox), with cache and history cleared.

Login error pops up.

![image](https://user-images.githubusercontent.com/31128624/57280947-235a2a00-70d4-11e9-85c1-e791a5fbe2d7.png)

**Comment by barbaraReliefapps** [comment]
This isn't an error, you tried to access the homepage at front.bmstaging.info but as you were not logged in you were redirected to the login page

**Comment by Happs80** [comment]
Understood, but can't we avoid this error popping up in this use case?
