### ISSUE TITLE
Test Server Error - Switching Countries Does't Change Page

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#653]
![image](https://user-images.githubusercontent.com/31128624/57345676-e8103780-7175-11e9-962b-72bebfcd2ecb.png)

**Comment by Nastaliss** [comment]
What do you mean ?
Changing country reloads the page with the country you selected and the same url.
Do you want to be redirected to the dashboard on changing country ?

**Comment by barbaraReliefapps** [comment]
Fixed in c4b6a46d7c6267de93c366a1dc6edee4dae8ce03
