### ISSUE TITLE
Icon Not Displaying on MS Edge - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#662]
![image](https://user-images.githubusercontent.com/31128624/57427684-39402a00-724f-11e9-8e0c-1440a422e5cd.png)

**Comment by barbaraReliefapps** [comment]
The platform was built for Chrome, Firefox and Safari (> v11), svg icons are not supported in Edge

**Comment by Happs80** [comment]
ok. if our designer provides .png images, this will be ok then?

**Comment by barbaraReliefapps** [comment]
Not really, we use svg icons on purpose as they are low size, high quality and can be customized. Switching to png would mean losing quality in terms of how the platform looks and how the future expansive map will look.

We can look at ways to have svg in Edge if we have time, but the platform was never designed for this browser

**Comment by barbaraReliefapps** [comment]
Actually, it seems like svg works on newer versions. What are you using? I just tested it on front-test and the icons were displayed correctly

**Comment by Happs80** [comment]
Yes, this seems to be ok now. thanks.
