### ISSUE TITLE
Visual Edit - Reports Page Issues - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#663]
- X Axis Titles Need Capitalisation
- X Axis Values should be integer, not decimal

![image](https://user-images.githubusercontent.com/31128624/57427981-853f9e80-7250-11e9-8eb8-ea590121adf5.png)

**Comment by Happs80** [comment]
Also, button text on MS Edge is hyphenating, when it should be just next line.
![image](https://user-images.githubusercontent.com/31128624/57428058-d2bc0b80-7250-11e9-8bbb-2784bf75b67c.png)

**Comment by barbaraReliefapps** [comment]
Hyphenation is on purpose for longer words
