### ISSUE TITLE
Project and Distribution Reports Do Not Appear to be Working - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#664]
![image](https://user-images.githubusercontent.com/31128624/57428103-0139e680-7251-11e9-8088-d07e0d11f879.png)

**Comment by barbaraReliefapps** [comment]
I think this is just because there is no reporting data saved for the projects/distributions, I generated the reporting data locally and it worked
![Screenshot from 2019-05-09 10-49-47](https://user-images.githubusercontent.com/36275616/57449061-43682580-725b-11e9-9b84-25887cd2076e.png)

**Comment by Happs80** [comment]
Please re-open.

There is definitely data there. This is the test we did Monday in Cambodia.

![image](https://user-images.githubusercontent.com/31128624/57499835-43276300-730b-11e9-9a01-076e2a105428.png)

**Comment by barbaraReliefapps** [comment]
Yes, and the reporting data is fetched at the end of every month, so it's normal that there's nothing yet

**Comment by Happs80** [comment]
Why is the reporting data fetched at the end of every month? Sometimes users will need to do distribution report straight after finishing distribution.

**Comment by barbaraReliefapps** [comment]
The reporting is meant for data visualisation over time, to show the evolution of certain data etc. As such we need to fetch the data and save the indicators in the database regularly (every month)
Exports of current database data are available immediatly

**Comment by Happs80** [comment]
Can we make this a manual fetch then? So users can get reporting information when they need it?

**Comment by barbaraReliefapps** [comment]
No that's not really possible; but we can make it update more often (but that means more data in the database)
