### ISSUE TITLE
Front End Beneficiary DB Display Seems to be Showing Incorrect Number

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#670]
![image](https://user-images.githubusercontent.com/31128624/57443777-0579fa00-7279-11e9-8a25-82ffbed1a849.png)

**Comment by barbaraReliefapps** [comment]
What do you mean by this?

**Comment by barbaraReliefapps** [comment]
Related to issue https://github.com/ReliefApplications/bms_front/issues/669 (fixed)
