### ISSUE TITLE
Finished Distribution Has Opened Again - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#707]
A Mobile Money Distribution which was completed seems to have 're-opened' again?

![image](https://user-images.githubusercontent.com/31128624/58022414-b1d79e00-7b0d-11e9-9564-2bce155011ea.png)

**Comment by barbaraReliefapps** [comment]
Investigating this, but not sure what happened. It is set as not validated in the database. Did you edit it?

**Comment by barbaraReliefapps** [comment]
Found the issue, won't happen with the new version. Since the distribution could still be edited even though it was validated, any changes switched it back to not validated
