### ISSUE TITLE
Visual Edit - Add Headers to Add Beneficiary Page - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#728]
On Page 1, we have 'Location' and 'Address' Headers.

On Page 2 and 3, could we add 'Name', 'ID', 'Residency' and 'Phone' headers?

![image](https://user-images.githubusercontent.com/31128624/58244646-5139a280-7d53-11e9-8e7d-a6ad4fc58961.png)

**Comment by Nastaliss** [comment]
Do you mean we should separate theses categories more clearly on these pages ?
