### ISSUE TITLE
UX Change - Add Beneficiary Project - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#731]
Need to change this to appear as an option after clicking Create.

![image](https://user-images.githubusercontent.com/31128624/58253661-396d1900-7d69-11e9-9484-52418997bc8c.png)

**Comment by Nastaliss** [comment]
Do you mean a modal that would pop up and ask you what projects to register the beneficiary in?

**Comment by Happs80** [comment]
Yes. Would be good! :

**Comment by barbaraReliefapps** [comment]
Modals are very intrusive in terms of user experience, and rarely used for a simple input

**Comment by Happs80** [comment]
True.

Is there a way to make the 'Select Project' element more visible, because i think it will be easy to miss at the moment?

**Comment by Happs80** [comment]
Still need to make this interaction better. Please re-open.

**Comment by Happs80** [comment]
?
