### ISSUE TITLE
Refactor reports

### ISSUE THREAD

**Issue by colinethrl** [ReliefApplications/bms_front#740]

**Comment by Happs80** [comment]
Country Report Total Funding Should be 'Dollars' and have $ and comma delimited.

![image](https://user-images.githubusercontent.com/31128624/58462168-9c77fa80-8131-11e9-867f-792a137e52ee.png)

**Comment by Happs80** [comment]
Project Report should be 'Households Served'.

![image](https://user-images.githubusercontent.com/31128624/58462222-ba455f80-8131-11e9-9c3a-5ed39c01210d.png)

**Comment by Happs80** [comment]
Y Axis 'Active Projects'

![image](https://user-images.githubusercontent.com/31128624/58629833-d423a580-82dd-11e9-8f6b-b08e7b46ccca.png)

**Comment by Happs80** [comment]
Y Axis should be 'Enrolled Beneficaries'

![image](https://user-images.githubusercontent.com/31128624/58630089-a25f0e80-82de-11e9-995a-d53c4b2ab44c.png)

**Comment by Happs80** [comment]
Title should be 'Number of Men & Women'

![image](https://user-images.githubusercontent.com/31128624/58630712-8fe5d480-82e0-11e9-977f-1f366813ce8b.png)

**Comment by Happs80** [comment]
Total household should be bar graph.

![image](https://user-images.githubusercontent.com/31128624/60176127-b894b780-9815-11e9-9703-1a4c355e0afb.png)

**Comment by Happs80** [comment]
Should be Total Number of Distributions Completed.

![image](https://user-images.githubusercontent.com/31128624/60176165-cba78780-9815-11e9-9337-ef7de0eda5a9.png)

**Comment by Happs80** [comment]
Graph should show ratio of men - women for whole project, not divided into distributions.

![image](https://user-images.githubusercontent.com/31128624/60176369-5d16f980-9816-11e9-9850-a08b32ff1a54.png)

**Comment by Happs80** [comment]
Title should be 'Types of Vulnerabilities Served (By %)'

![image](https://user-images.githubusercontent.com/31128624/60176412-7cae2200-9816-11e9-9dbb-a008a467b348.png)

**Comment by Happs80** [comment]
Project Timeline should revert to Maximum and then be able to select time periods.

![image](https://user-images.githubusercontent.com/31128624/60176503-c0089080-9816-11e9-8453-948959532932.png)

**Comment by Happs80** [comment]
What is this value under Distributions Reports?

![image](https://user-images.githubusercontent.com/31128624/60176542-e5959a00-9816-11e9-9eb5-d93b1102996e.png)

**Comment by Happs80** [comment]
Also, what do these values represent?

![image](https://user-images.githubusercontent.com/31128624/60176569-fc3bf100-9816-11e9-9555-fd4815e5d225.png)

**Comment by Nastaliss** [comment]
Fixed in #763
