### ISSUE TITLE
Table Header - ID Should Be HouseholdID - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#741]
![image](https://user-images.githubusercontent.com/31128624/58404007-69b40080-8064-11e9-8303-d60cca905b5a.png)

**Comment by barbaraReliefapps** [comment]
For the moment this is ID as it is simply the automatic database ID (as you required previously), not to be confused with a specific ID

**Comment by Happs80** [comment]
Sure, understood. Is it possible to change the table title though?
