### ISSUE TITLE
Visual Edit - Standard Drop Shadow - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#744]
Many of the buttons and tables have different drop shadows. Can we choose one standard and stick with it.

![image](https://user-images.githubusercontent.com/31128624/58463264-cf22f280-8133-11e9-990c-033c32d9899c.png)

**Comment by barbaraReliefapps** [comment]
All buttons have the same, and all boxes have the same
We will adjust the "no data" on this page.
