### ISSUE TITLE
File Import Error - Critical

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#790]
This error is occurring when trying to import files.

![image](https://user-images.githubusercontent.com/31128624/59847524-06677680-9363-11e9-97a0-60bb18dfa4a3.png)

**Comment by barbaraReliefapps** [comment]
We haven't been able to reproduce the issue locally or on the test server

**Comment by Happs80** [comment]
We can close this now, yes?

But with a note to look at duplication checks again in the future at some point.
