### ISSUE TITLE
Project Not Showing Assigned Beneficiaries - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#792]
![image](https://user-images.githubusercontent.com/31128624/59848373-47f92100-9365-11e9-8d88-b79e32420d54.png)

![image](https://user-images.githubusercontent.com/31128624/59848392-51828900-9365-11e9-894c-79da32de6573.png)

**Comment by barbaraReliefapps** [comment]
These are two different projects, one one which is archived (the one on the beneficiary list)
<img width="396" alt="Capture d’écran 2019-06-21 à 00 17 27" src="https://user-images.githubusercontent.com/36275616/59868106-2c6c3580-93ba-11e9-8b19-24be403bc117.png">
