### ISSUE TITLE
QR Voucher Cannot Be Selected as Modality - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#800]
Can only select Paper Voucher currently.

![image](https://user-images.githubusercontent.com/31128624/59857449-433e6800-9379-11e9-808e-cf895f34d950.png)

**Comment by barbaraReliefapps** [comment]
That's because we have to reset the database or add it manually

**Comment by Happs80** [comment]
ok so this will appear as an option when you do the next release (and reset the db)?
