### ISSUE TITLE
Remove 'Status' from Create New Booklet Modal & Change Title - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#807]
Title should be: Create New Voucher Booklets

![image](https://user-images.githubusercontent.com/31128624/59918112-14310080-9424-11e9-8b58-8a6bc052de72.png)

**Comment by barbaraReliefapps** [comment]
Not sure if we can remove status since the fields are generated automatically

**Comment by Happs80** [comment]
Is it possible to 'hide' it then?
