### ISSUE TITLE
Add Currency to Validated Distribution Table - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#852]

**Comment by barbaraReliefapps** [comment]
Not sure what you mean by that, could we have more information?

**Comment by Happs80** [comment]
On QR Code Voucher Validated Distribution page, in the table under the value column, could we please show the currency as well?

![image](https://user-images.githubusercontent.com/31128624/60714522-83761c80-9f1b-11e9-9448-5ad637ac3352.png)

Same as how it is for 'general' distributions.

![image](https://user-images.githubusercontent.com/31128624/60714567-94bf2900-9f1b-11e9-9c74-634c4c67ef93.png)
