### ISSUE TITLE
User Registered in SYR logged into KHM - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#857]
![image](https://user-images.githubusercontent.com/31128624/60651358-5441ab80-9e46-11e9-929e-3d2e8c9ff634.png)

**Comment by Happs80** [comment]
![image](https://user-images.githubusercontent.com/31128624/60651413-6d4a5c80-9e46-11e9-8096-6345e6e8413c.png)

**Comment by barbaraReliefapps** [comment]
However I tried, I haven't been able to reproduce this

**Comment by Happs80** [comment]
Tried myself and is occurring for me too.

![image](https://user-images.githubusercontent.com/31128624/60677287-655bde00-9e81-11e9-82e1-68a097911051.png)

**Comment by barbaraReliefapps** [comment]
Might be an issue with the current version of the app, we'll check if it is still happening after tomorrow's release

**Comment by Happs80** [comment]
For further information, now i have logged back into my own account and I cannot change countries anymore. Nothing happens when i click the location icon.

![image](https://user-images.githubusercontent.com/31128624/60686594-1c6c4f80-9eaa-11e9-846a-74abdc2c1b6d.png)

**Comment by barbaraReliefapps** [comment]
Has this happened again since the release?

**Comment by Happs80** [comment]
Yes. Only one user thus far though.

![image](https://user-images.githubusercontent.com/31128624/60789481-7c3f5080-a15f-11e9-98f1-260a2c12bf02.png)

**Comment by barbaraReliefapps** [comment]
Could you ask him to clear his cache and see if the problem persists?

**Comment by Happs80** [comment]
Already done.
