### ISSUE TITLE
Visual Edit - Switch Back to Mapbox Light - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#882]
![image](https://user-images.githubusercontent.com/31128624/60758665-29a84c00-a01a-11e9-80fb-67adc2e0fd55.png)

**Comment by barbaraReliefapps** [comment]
Are you sure? Part of the specifications for the Stage 2 was using OSM

**Comment by Happs80** [comment]
Ok let's leave it as OSM.

Can we change the layer to 'Humanitarian' layer?

https://www.openstreetmap.org/search?query=syria#map=7/34.853/38.923&layers=H
