### ISSUE TITLE
Date Check for Distributions Should be <CurrentDate NOT ≤ CurrentDate - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#906]
![image](https://user-images.githubusercontent.com/31128624/60813529-3f418100-a194-11e9-8bee-8697272c5e6c.png)

**Comment by barbaraReliefapps** [comment]
The other way around no?

**Comment by Happs80** [comment]
As in...... It is not allowing distributions to be created on the same day. When it should.

Is that more clear? :)
