### ISSUE TITLE
Too Many Confirmation Boxes When Assigning Vouchers - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#948]
![image](https://user-images.githubusercontent.com/31128624/61176122-8e841900-a5bb-11e9-905b-6310e0251f79.png)

**Comment by barbaraReliefapps** [comment]
What do you mean? The process has multiple steps

**Comment by Happs80** [comment]
Yes. Can skip the first popup, if possible. Go straight to open camera.

![image](https://user-images.githubusercontent.com/31128624/61202354-92ad5500-a6e7-11e9-8802-86f342049019.png)

And can we combine the password question and confirmation modal into one modal?
