### ISSUE TITLE
System Randomly Logging Me Out. Stable Internet Connection. - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#951]
![image](https://user-images.githubusercontent.com/31128624/61176296-b88b0a80-a5be-11e9-8e32-b51928eceeeb.png)

**Comment by Happs80** [comment]
Error Message: You are not authenticated.

**Comment by barbaraReliefapps** [comment]
Did this happen on specific pages?

**Comment by Happs80** [comment]
Typically when trying to open Distribution Page.

**Comment by Happs80** [comment]
FYI. This is still occurring.
