### ISSUE TITLE
Preferable to have Text Underneath the Button for Selected Items - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#959]
For example

![image](https://user-images.githubusercontent.com/31128624/61200904-35170980-a6e3-11e9-9ae6-504de0172e1d.png)

![image](https://user-images.githubusercontent.com/31128624/61200878-24ff2a00-a6e3-11e9-9024-d89a6a0796a5.png)

**Comment by Happs80** [comment]
No numbers needed if nothing selected.

**Comment by barbaraReliefapps** [comment]
Not sure what you mean. Adding a second line under the button will move the page content down when something is selected and may look stranger

**Comment by Happs80** [comment]
Can it not align with the search bar?
