### ISSUE TITLE
Visual Edit - Many Fields Have Strange Text Floating Location - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#960]
Should be aligned to the line at the bottom.

![image](https://user-images.githubusercontent.com/31128624/61201414-b9b65780-a6e4-11e9-942e-30dedef12d8d.png)

**Comment by barbaraReliefapps** [comment]
This is for text areas, multiple line inputs

**Comment by Happs80** [comment]
Can we not align the 'hint' text with the bottom of the box?

**Comment by bamoure** [comment]
It aligns in the middle

**Comment by Happs80** [comment]
Can we align it lower?
