### ISSUE TITLE
User Password Change Function - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#966]
When user is directed to profile page to change password, need a popup to alert them that they are being directed there to change their password.

**Comment by barbaraReliefapps** [comment]
There's already one
<img width="650" alt="Capture d’écran 2019-07-15 à 10 33 36" src="https://user-images.githubusercontent.com/36275616/61203911-094c5180-a6ec-11e9-829d-cdfa75ccf43b.png">

**Comment by Happs80** [comment]
Ahah. Could it be green?

**Comment by barbaraReliefapps** [comment]
Sure!
