### ISSUE TITLE
Visual Edit - Change Marker to Style Guide Yellow - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#979]
#cefa05

![image](https://user-images.githubusercontent.com/31128624/61278195-0026b780-a7b4-11e9-9e0c-19023f31e964.png)

**Comment by bamoure** [comment]
Markers are green when there are <10 distributions, yellow when there are <100 distributions and red when there are >100 distributions
Should we have them in yellow no matter the count?

**Comment by Happs80** [comment]
Oh i see, could we have bigger marker instead?

**Comment by Happs80** [comment]
as in, >50 2cm diameter, etc...
