### ISSUE TITLE
Cannot Change Country - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#986]
Logged in as admin to SYR, but cannot find KHM.

**Comment by bamoure** [comment]
Did you clear your cache and do a hard reset?

**Comment by Happs80** [comment]
I did a hard reset, but not cleared the cache.

**Comment by Happs80** [comment]
ok i cleared the cache on firefox and still cannot change country.

**Comment by bamoure** [comment]
Can you try again? There was an issue with the db

**Comment by Happs80** [comment]
yes. thanks! works again now. (although it's no longer saving my last login country as it did previously).
