### ISSUE TITLE
Change Distribution Naming Convention - Low

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#994]
Change distribution name from DistLocation-Date to DistSelection-Date.

So for example ..... CampName-09-09-19 or VillageName08-08-19

**Comment by bamoure** [comment]
This will be complicated since there can be multiple selection criteria, and it will quickly become illegible / too long

**Comment by Happs80** [comment]
What about only ADM4 or Camp Name?

**Comment by bamoure** [comment]
These aren't available for all distributions
With location we pick the most precise one, so adm4 if it exists

**Comment by Happs80** [comment]
ah damn. ok. let's forget for now. i'll ask the team to use distID as a reference.
